In [2]:
import pandas as pd
import numpy as np

In [4]:
fusion = pd.read_csv('../data/crc_raw/cBioPortal_files/data_fusions.txt', sep='\t')
fusion.head()

,Hugo_Symbol,Entrez_Gene_Id,Center,Tumor_Sample_Barcode,Fusion,DNA_support,RNA_support,Method,Frame
0,PARK2,NaN,MSK,GENIE-MSK-P-0002702-T01-IM3,PARK2-intragenic,yes,unknown,NaN,unknown
1,RNF43,NaN,MSK,GENIE-MSK-P-0004140-T01-IM5,RNF43-intragenic,yes,unknown,NaN,in frame
2,BRAF,NaN,MSK,GENIE-MSK-P-0004140-T01-IM5,BRAF-intragenic,yes,unknown,NaN,in frame
3,TP53,NaN,MSK,GENIE-MSK-P-0004140-T02-IM5,TP53-intragenic,yes,unknown,NaN,unknown
4,LATS2,NaN,MSK,GENIE-MSK-P-0004401-T01-IM5,ATP8A2-LATS2 fusion,yes,unknown,NaN,out of frame

In [5]:
len(fusion['Hugo_Symbol'].unique())

256

In [6]:
gene_list = fusion['Hugo_Symbol'].unique()
sample_list = fusion['Tumor_Sample_Barcode'].unique()
len(sample_list)

254

In [7]:
data = pd.DataFrame(index=sample_list, columns=gene_list)

In [8]:
for i, row in fusion.iterrows():
    data.loc[row['Tumor_Sample_Barcode'], row['Hugo_Symbol']] = 1

In [9]:
data.head()

,PARK2,RNF43,BRAF,TP53,LATS2,TSC2,GPS2,FYN,EP300,TCF7L2,...,MYBL1,CAPN13,CREBBP,LRP1B,TRA,CIC,RSPO2,COL7A1,C8orf37,TP53
GENIE-MSK-P-0002702-T01-IM3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GENIE-MSK-P-0004140-T01-IM5,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GENIE-MSK-P-0004140-T02-IM5,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GENIE-MSK-P-0004401-T01-IM5,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GENIE-MSK-P-0004967-T01-IM5,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data.fillna(0, inplace=True)
data.head()

,PARK2,RNF43,BRAF,TP53,LATS2,TSC2,GPS2,FYN,EP300,TCF7L2,...,MYBL1,CAPN13,CREBBP,LRP1B,TRA,CIC,RSPO2,COL7A1,C8orf37,TP53
GENIE-MSK-P-0002702-T01-IM3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GENIE-MSK-P-0004140-T01-IM5,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GENIE-MSK-P-0004140-T02-IM5,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GENIE-MSK-P-0004401-T01-IM5,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GENIE-MSK-P-0004967-T01-IM5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
data.to_csv('../data/crc_fusion.csv')